/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e205714;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class GameMasterTest {

    @Test 
    void shootPositionTest(){
        int shoot=4;//シュートする側が選んだシュートポイント
        int keep=4;//キーパーがボールが来ると予想したポイント
        int correctCount=0;
        GameMaster gameMaster=new GameMaster();
        Character player1=new Player();//シュートする側
        Character player2=new Player();//キーパー側
        player1.setShoot(shoot);
        player2.setKeep(keep);
        gameMaster.goalJudge(player1,player2);
        if(player1.getScore()==0){
            correctCount++;
        }
        player1.setShoot(shoot+1);
        player2.setKeep(keep-1);
        gameMaster.goalJudge(player1,player2);
        if(player1.getScore()==1){
            correctCount++;
        }
        player1.setShoot(shoot-3);
        player2.setKeep(keep-1);
        gameMaster.goalJudge(player1,player2);
        if(player1.getScore()==2){
            correctCount++;
        }
        assertEquals(3, correctCount);
    }



    /*
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    */
}
